name: SocialSpy
api: [3.0.0]
version: 1.0.0
main: SocialSpy\superbobby2000\Main
author: superbobby2000
description: Allows you to see commands.
commands:
  socialspy:
    description: "Turn on socialspy"
    permission: "socialspy.command"
    aliases:
      - ss
permissions:
  socialspy.command:
    description: "Allow you to use socialspy command"
    default: op
  socialspy.hide:
    description: "hide your commands from SocialSpy"
    default: op
